---
deployment:
  tasks:
    - export DEPLOYPATH=/home/somapiauic/public_html/landing-page-soma
    - npm install  # Instala as dependências
    - npm run build  # Gera os arquivos estáticos na pasta dist/
    - /bin/cp -R dist/* $DEPLOYPATH
